
const EPOCH_HOURS = 24 ;// 10/60 //1 minute

export class Config{
  DATE_FORMAT_PATTERN = 'YYYY-MM-DDTHH:mm:ss [GMT]Z'

 
  RECONNECT_WAIT_TIME = 1
  RECONNECT_WAIT_ENABLED = true

  //this is temporary hardcodes
  
  PLAYFAB_ENABLED = process.env.PLAYFAB_ENABLED === undefined || (process.env.PLAYFAB_ENABLED !== undefined && process.env.PLAYFAB_ENABLED === 'true')
  PLAYFAB_TITLEID = process.env.PLAYFAB_TITLEID
  PLAYFAB_DEVELOPER_SECRET = process.env.PLAYFAB_DEVELOPER_SECRET

  //if true, will catch and log them but not bomb the game out
  SILENCE_UNHANDLED_ERRORS = process.env.SILENCE_UNHANDLED_ERRORS === undefined || (process.env.SILENCE_UNHANDLED_ERRORS !== undefined && process.env.SILENCE_UNHANDLED_ERRORS === 'true')

  //default is true
  ON_JOIN_REQUIRE_PLAYFAB_DATA_OPTIONS = process.env.ON_JOIN_REQUIRE_PLAYFAB_DATA_OPTIONS === undefined || (process.env.ON_JOIN_REQUIRE_PLAYFAB_DATA_OPTIONS !== undefined && process.env.ON_JOIN_REQUIRE_PLAYFAB_DATA_OPTIONS === 'true')
  
  //DEFAULT npc room
  NPC_ROOM_INWORLD_KEY = process.env.NPC_ROOM_INWORLD_KEY !== undefined ? process.env.NPC_ROOM_INWORLD_KEY : "PROVIDE NPC_ROOM_INWORLD_KEY"
  NPC_ROOM_INWORLD_SECRET = process.env.NPC_ROOM_INWORLD_SECRET !== undefined ? process.env.NPC_ROOM_INWORLD_SECRET : "PROVIDE NPC_ROOM_INWORLD_SECRET"
  NPC_ROOM_INWORLD_SCENE = process.env.NPC_ROOM_INWORLD_SCENE !== undefined ? process.env.NPC_ROOM_INWORLD_SCENE : "PROVIDE NPC_ROOM_INWORLD_SCENE"

  //explicit npc room
  GENESIS_CITY_NPC_ROOM_INWORLD_KEY = process.env.GENESIS_CITY_NPC_ROOM_INWORLD_KEY !== undefined ? process.env.GENESIS_CITY_NPC_ROOM_INWORLD_KEY : "PROVIDE GENESIS_CITY_NPC_ROOM_INWORLD_KEY"
  GENESIS_CITY_NPC_ROOM_INWORLD_SECRET = process.env.GENESIS_CITY_NPC_ROOM_INWORLD_SECRET !== undefined ? process.env.GENESIS_CITY_NPC_ROOM_INWORLD_SECRET : "PROVIDE GENESIS_CITY_NPC_ROOM_INWORLD_SECRET"
  GENESIS_CITY_NPC_ROOM_INWORLD_SCENE = process.env.GENESIS_CITY_NPC_ROOM_INWORLD_SCENE !== undefined ? process.env.GENESIS_CITY_NPC_ROOM_INWORLD_SCENE : "PROVIDE GENESIS_CITY_NPC_ROOM_INWORLD_SCENE"

}

export const CONFIG = new Config()

//console.log("CONFIG",CONFIG)